name: example
description: Example using Flutter Duration Picker
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  duration_time_picker:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true