name: duration_time_picker
description: A time picker widget that can select both minutes and hours. Fork from flutter_duration_picker.
version: 1.0.0
homepage: https://github.com/cledsonv/duration_time_picker

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1