name: duration_picker
description: A time picker widget. Fork from flutter_duration_picker.
version: 1.0.0
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  pedantic: ^1.11.0
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter: